from openai import OpenAI
import pandas as pd
import requests
from pprint import pprint

class Agent:
    def __init__(self, name, role):
        self.name = name
        self.role = role

    def run(self, task, extra_prompt=""):
        print(f"{self.name} is working...")

        return self.process(task, extra_prompt)

    def process(self, task, extra_prompt=""):
        raise NotImplementedError


def load_data(file_path):
    if file_path.endswith(".csv"):
        df = pd.read_csv(file_path)

    elif file_path.endswith(".xlsx"):
        df = pd.read_excel(file_path)

    else:
        raise ValueError("Only CSV and Excel supported")

    print("-- Data Loaded Successfully --")
    print(df.head())
    return df
class DataCleaningAgent(Agent):
    def process(self, df, extra_prompt=""):

        report = {}

        # Missing values
        missing = df.isnull().sum()
        report["missing_values"] = missing.to_dict()

        # Drop duplicates
        before = df.shape[0]
        df = df.drop_duplicates()
        after = df.shape[0]

        report["duplicates_removed"] = before - after

        # Fill missing values
        df = df.fillna(df.median(numeric_only=True))

        report["final_shape"] = df.shape

        return df, report
    
class EDAAgent(Agent):
    def process(self, df, extra_prompt=""):

        report = {}

        report["shape"] = df.shape
        report["columns"] = list(df.columns)
        report["data_types"] = df.dtypes.astype(str).to_dict()

        report["summary_stats"] = df.describe().to_dict()

        # Correlation (numeric only)
        report["correlation"] = df.corr(numeric_only=True).to_dict()

        return df, report

class KPIAgent(Agent):
    def process(self, df, extra_prompt=""):

        kpis = {}

        # Try common business columns safely
        if "sales" in df.columns:
            kpis["total_sales"] = df["sales"].sum()
            kpis["avg_sales"] = df["sales"].mean()

        if "revenue" in df.columns:
            kpis["total_revenue"] = df["revenue"].sum()

        if "profit" in df.columns:
            kpis["total_profit"] = df["profit"].sum()

        if "customer_id" in df.columns:
            kpis["total_customers"] = df["customer_id"].nunique()

        return df, kpis

YOUR_API_KEY = "HERE GOES"

def call_llm(prompt):
    response = requests.post(
        url="https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {YOUR_API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "http://localhost",
            "X-Title": "MultiAgentAI"
        },
        json={
            "model": "openai/gpt-4o-mini",
            "messages": [
                {"role": "user", "content": prompt}
            ]
        }
    )

    data = response.json()

    return data["choices"][0]["message"]["content"]

class InsightAgent(Agent):
    def process(self, data, extra_prompt=""):

        prompt = f"""
You are a senior business analyst.

DATA SUMMARY:
Columns: {list(data.columns)}
Shape: {data.shape}

EDA/KPI INFO:
{extra_prompt}

Task:
- Generate insights
- Identify risks
- Suggest improvements
"""

        return call_llm(prompt)

class ReportAgent(Agent):
    def process(self, data, extra_prompt=""):

        report = f"""
========================
📊 FINAL BUSINESS REPORT
========================

Dataset Shape: {data.shape}

Columns:
{list(data.columns)}

SUMMARY:
{extra_prompt}

========================
Generated by Multi-Agent System
========================
"""
        return report

file_path = r'C:\Users\danup\Downloads\shopping_trends.csv'   # or .xlsx

df = load_data(file_path)

# Agents
cleaner = DataCleaningAgent("Cleaner", "")
eda = EDAAgent("EDA", "")
kpi = KPIAgent("KPI", "")
insight = InsightAgent("Insight", "")
report = ReportAgent("Report", "")

# Step 1: Cleaning
df, clean_report = cleaner.process(df)
df, eda_report = eda.process(df)
df, kpi_report = kpi.process(df)

insight_input = {
    "cleaning": clean_report,
    "eda": eda_report,
    "kpi": kpi_report
}

insight_report = insight.run(df, extra_prompt=str({
    "cleaning": clean_report,
    "eda": eda_report,
    "kpis": kpi_report
}))
# Step 5: Final Report
final_report = report.run(df, extra_prompt=f"""
Cleaning: {clean_report}
EDA: {eda_report}
KPI: {kpi_report}
Insights: {insight_report}
""")

print("""
========================
CLEANING REPORT
========================
""")
pprint(clean_report)

print("""
========================
EDA REPORT
========================
""")
pprint(eda_report)

print("""
========================
KPI REPORT
========================
""")
pprint(kpi_report)

print("""
========================
INSIGHTS
========================
""") 
pprint(insight_report)

print("""
========================
FINAL REPORT
========================
""")
pprint(final_report)
